import pandas as pd
import glob
import os

# --- 1. Settings: Configuration Section ---

# 1. Directory containing the new Cardiff data files
DATA_FOLDER = r'/Users/yahye/Downloads/Liverpool Speke'

# 2. Filename for the final processed output
OUTPUT_FILE = "Liverpool_COMBINED_CLEAN.csv"

# 3. Row number to use as the header (0-based index, so 10 is the 11th row)
HEADER_ROW_NUMBER = 10 

# 4. Exact column names as they appear in the source CSVs
DATE_COLUMN_NAME = 'Date'
TIME_COLUMN_NAME = 'Time'

# 5. Format string for the time column
TIME_FORMAT = '%H:%M:%S' # Matches '01:00:00'

# 6. Mapping dictionary to standardise column names
COLUMN_RENAME_MAP = {
    'Nitrogen dioxide': 'NO2',
    'PM10 particulate matter (Hourly measured)': 'PM10',
    'PM2.5 particulate matter (Hourly measured)': 'PM25', # Standardise to PM25
    'Modelled Wind Direction': 'M_DIR',
    'Modelled Wind Speed': 'M_SPED',
    'Modelled Temperature': 'M_T'
}

# 7. List of standardised columns to retain in the final dataset
COLUMNS_TO_KEEP = [
    'datetime',  # Generated by this script
    'NO2',
    'PM10',
    'PM25',
    'M_T',
    'M_SPED',
    'M_DIR'
]
# --- End of Configuration ---


print(f"--- Starting: Combining all CSVs in folder: {DATA_FOLDER} ---")

csv_files = glob.glob(os.path.join(DATA_FOLDER, "*.csv"))

if not csv_files:
    print(f"ERROR: No .csv files found in '{DATA_FOLDER}'.")
    print("Please check the path in the DATA_FOLDER variable.")
else:
    print(f"Found {len(csv_files)} files to combine...")

# --- 2. Read and Combine Files ---
df_list = []
for file in csv_files:
    print(f"Processing {file}...")
    try:
        # Load CSV using the specified header row
        df = pd.read_csv(file, header=HEADER_ROW_NUMBER, low_memory=False) 

        # Rename columns according to the mapping dictionary
        df = df.rename(columns=COLUMN_RENAME_MAP)
        
        # Verify essential columns exist
        if DATE_COLUMN_NAME not in df.columns or TIME_COLUMN_NAME not in df.columns:
            print(f"  ERROR: File '{file}' is missing '{DATE_COLUMN_NAME}' or '{TIME_COLUMN_NAME}' columns.")
            print(f"  This file might have a different structure. Skipping this file.")
            print(f"  (Its columns are: {df.columns.to_list()})")
            continue 
            
        # Ensure PM2.5 naming consistency
        if 'PM2.5' in df.columns:
            df = df.rename(columns={'PM2.5': 'PM25'})
            
        df_list.append(df)
    except Exception as e:
        print(f"  Could not read {file}. Error: {e}")

if not df_list:
    print("\nERROR: No files were successfully read and processed.")
    print("Please check the error messages above to fix your CSV files.")
else:
    # Concatenate all valid DataFrames into a single object
    combined_df = pd.concat(df_list, ignore_index=True)

    print("\nAll valid files combined. Now cleaning data...")

    # --- 3. Clean the Combined Data ---
    
    # Standardise midnight representation (replace '24:00:00' with '00:00:00')
    combined_df[TIME_COLUMN_NAME] = combined_df[TIME_COLUMN_NAME].replace('24:00:00', '00:00:00')

    print("  Combining and converting to datetime...")
    try:
        # 1. Merge Date and Time columns into a single string
        datetime_str = combined_df[DATE_COLUMN_NAME] + ' ' + combined_df[TIME_COLUMN_NAME]

        # 2. Convert to datetime objects
        combined_df['datetime'] = pd.to_datetime(
            datetime_str, 
            format=f'%Y-%m-%d {TIME_FORMAT}', 
            errors='coerce' 
        )
        
    except Exception as e:
        print(f"\nCRITICAL ERROR: Could not combine Date and Time. Error: {e}")
        # Terminate execution on critical failure
        exit()
    
    # 3. Adjust dates for midnight values (add one day to '00:00:00' entries originally marked as '24:00:00')
    mask_24h = (combined_df[TIME_COLUMN_NAME] == '00:00:00') & (combined_df['datetime'].notna())
    combined_df.loc[mask_24h, 'datetime'] += pd.Timedelta(days=1)

    # Set the new datetime column as the DataFrame index
    combined_df = combined_df.set_index('datetime').sort_index()

    # Create a new DataFrame for the final output
    final_df = pd.DataFrame(index=combined_df.index)

    print("  Selecting and converting final columns...")
    for col in COLUMNS_TO_KEEP:
        if col in combined_df.columns:
            # Coerce column data to numeric types
            final_df[col] = pd.to_numeric(combined_df[col], errors='coerce')
        elif col != 'datetime':
            print(f"  Warning: Standardised column '{col}' not found. Skipping.")

    # Remove rows where all key data columns are missing
    final_df = final_df.dropna(how='all', subset=[col for col in COLUMNS_TO_KEEP if col != 'datetime'])

    # --- 4. Save the Final, Clean File ---
    final_df.to_csv(OUTPUT_FILE)

    print(f"\nSuccess! Clean, combined file saved as '{OUTPUT_FILE}'")
    print("\n--- Final Data Info ---")
    final_df.info()
    print("\n--- Final Data Head ---")
    print(final_df.head())
